# Generated by Django 6.0 on 2026-01-03 06:16

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("work", models.CharField(blank=True, max_length=100)),
                ("education", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "profile_pic",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default="https://res.cloudinary.com/demo/image/upload/v1690000000/default-avatar.png",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                (
                    "cover_photo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default="https://res.cloudinary.com/demo/image/upload/v1690000000/default-cover.jpg",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
